### ISSUE TITLE
src/main.exe doesn't do as described in README.md

### ISSUE THREAD

**Issue by hannesm** [dinosaure/bechamel#2]
your recent commits changed the behaviour of main.exe, and I don't understand what I need to do to get back the notty backend. maybe the json stuff should be a different executable or a command-line flag?

thanks, hannes

**Comment by dinosaure** [comment]
Ah yes, I update `main.exe` to produce a JSON which can be used by the _HTML back-end_ and show you more details than the `notty`. I would like to say that the _HTML back-end_ is more precise and should be used instead of the `notty` back-end where it show you samples.

However, if you prefer to continue to use the `notty` back-end, I can keep the example :+1: .

**Comment by hannesm** [comment]
if this is the case, I'm as well happy with the json, but I failed to find any documentation on how to use the HTML/js backend...

**Comment by dinosaure** [comment]
I yes, so to use it:
```sh
$ dune exec src/main.exe > html/outputs.json
$ firefox html/index.html
```

I would like to produce something which is completely self-contained but I did not find a _good_ solution currently.

**Comment by dinosaure** [comment]
I think this issue was fixed by the last release of `bechamel` where I provide several executables for each backends:
- `examples/fact.exe` for the JSON output
- `examples/list.exe` for the `Notty` output
- `examples/sqrt.exe` without any backend but it uses `Bechamel_perf`/`perf` to record samples
